import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./lib/AuthContext";
import { FaHome, FaSignInAlt, FaUserPlus } from "react-icons/fa";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex min-h-screen">

          <aside className="w-64 bg-gray-800 text-white flex flex-col items-center py-4">
            <nav className="space-y-4 w-full px-4">
              <a
                href="/"
                className="flex items-center gap-3 px-4 py-2 text-sm font-medium rounded-lg hover:bg-gray-700"
              >
                <FaHome className="text-lg" /> Strona główna
              </a>
              <a
                href="/public/user/signin"
                className="flex items-center gap-3 px-4 py-2 text-sm font-medium rounded-lg hover:bg-gray-700"
              >
                <FaSignInAlt className="text-lg" /> Logowanie
              </a>
              <a
                href="/public/user/register"
                className="flex items-center gap-3 px-4 py-2 text-sm font-medium rounded-lg hover:bg-gray-700"
              >
                <FaUserPlus className="text-lg" /> Rejestracja
              </a>
            </nav>
          </aside>

          {/* Główna zawartość */}
          <div className="flex-1 flex flex-col">
            {/* Górny pasek */}
            <header className="bg-pink-300 text-white py-3 px-6 shadow-md flex justify-between items-center">
              <h1 className="text-xl font-bold">Quiz app</h1>
              <div className="space-x-4">
                <a
                  href="/public/user/signin"
                  className="px-4 py-2 bg-gray-700 rounded-md text-sm font-medium hover:bg-gray-600"
                >
                  Logowanie
                </a>
                <a
                  href="/public/user/register"
                  className="px-4 py-2 bg-gray-700 rounded-md text-sm font-medium hover:bg-gray-600"
                >
                  Rejestracja
                </a>
              </div>
            </header>

            {/* Główna treść */}
            <main className="flex-1 container mx-auto py-6 px-4">
              <AuthProvider>{children}</AuthProvider>
            </main>

            {/* Stopka */}
            <footer className="bg-gray-800 text-white py-4 text-center">
              &copy; 2024 Quiz App React - Justyna Malinowska
            </footer>
          </div>
        </div>
      </body>
    </html>
  );
}
